# Generated by Django 4.1.3 on 2022-12-03 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_banquet_halls_price'),
    ]

    operations = [
    ]
