# Generated by Django 4.1.3 on 2022-12-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterer_name', models.CharField(max_length=50)),
                ('catering_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_name', models.CharField(max_length=50)),
                ('dj_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='florist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('florist_name', models.CharField(max_length=100)),
                ('florist_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='lighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_name', models.CharField(max_length=50)),
                ('lighting_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_name', models.CharField(max_length=50)),
                ('photographer_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='banquet_halls',
            old_name='manager',
            new_name='manager_name',
        ),
        migrations.AddField(
            model_name='banquet_halls',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='banquet_halls',
            name='Price',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=10, upload_to='')),
                ('banquet_halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.banquet_halls')),
            ],
        ),
    ]
