# Generated by Django 4.1.3 on 2022-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_catering_dj_florist_lighting_photographer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='dj',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='florist',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='lighting',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='photographer',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
